[project]
name = "lendpool-backend"
version = "0.1.0"
description = "Backend for LendPool P2P Lending"
authors = [
    {name = "Antigravity",email = "antigravity@google.com"}
]
requires-python = "^3.12"
dependencies = [
    "fastapi (>=0.135.3,<0.136.0)",
    "uvicorn (>=0.42.0,<0.43.0)",
    "algokit-utils (>=4.2.3,<5.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
